/*
 * Copyright 2021 EPAM Systems.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.epam.digital.data.platform.generator.metadata;

public class AutoGeneratedValue {

  private static final String SEQUENCE_PATTERN = "%s_%s_seq";
  
  private final String column;
  private final String sequenceName;
  private final String pattern;

  public AutoGeneratedValue(String table, String column, String pattern) {
    this.column = column;
    this.sequenceName = String.format(SEQUENCE_PATTERN, table, column);
    this.pattern = pattern;
  }

  public String getColumn() {
    return column;
  }

  public String getSequenceName() {
    return sequenceName;
  }

  public String getPattern() {
    return pattern;
  }
}
