/*
 * Copyright 2021 EPAM Systems.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.epam.digital.data.platform.generator.metadata;

import static java.util.stream.Collectors.toList;

import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;
import org.springframework.stereotype.Component;

@Component
public class AutoGeneratedValueProvider {

  static final String AUTO_GENERATE_CHANGE_TYPE = "autoGenerate";

  private final MetadataFacade metadataFacade;
  private final Set<String> tablesWithAutoGeneratedValues;

  public AutoGeneratedValueProvider(MetadataFacade metadataFacade) {
    this.metadataFacade = metadataFacade;
    tablesWithAutoGeneratedValues = metadataFacade.findByChangeType(AUTO_GENERATE_CHANGE_TYPE)
        .map(Metadata::getChangeName)
        .collect(Collectors.toSet());
  }

  public List<AutoGeneratedValue> findFor(String tableName) {
    return metadataFacade
        .findByChangeTypeAndChangeName(AUTO_GENERATE_CHANGE_TYPE, tableName)
        .map(metadata -> new AutoGeneratedValue(tableName, metadata.getName(), metadata.getValue()))
        .collect(toList());
  }

  public Set<String> getTablesWithAutoGeneratedValues() {
    return tablesWithAutoGeneratedValues;
  }
}
