apiVersion: v1
kind: ConfigMap
metadata:
  name: soap-api-properties
data:
  config.yaml: |-
    rest-api:
      url: {{ .Values.restApi.url }}.{{ .Values.ciProject }}.svc:8080

    audit:
      kafka:
        bootstrap: {{ .Values.kafka.service }}
        topic: {{ .Values.audit.kafka.topic }}
        schema-registry-url: {{ .Values.audit.kafka.schemaRegistryUrl }}

    keycloak:
      server-url: {{ .Values.keycloak.url }}/auth
      service-account:
        realm: {{ .Values.ciProject }}-external-system
        client-id: {{ .Values.keycloak.serviceAccount.clientId }}
