apiVersion: v1
kind: ConfigMap
metadata:
  name: soap-api-properties
data:
  config.yaml: |-
    management:
      endpoints:
        web:
          exposure:
            include: 'health, prometheus'    
    rest-api:
      url: {{ .Values.restApi.url }}.{{ .Values.ciProject }}.svc:8080

    audit:
      kafka:
        bootstrap: {{ .Values.kafka.service }}
        topic: {{ .Values.audit.kafka.topic }}
        schema-registry-url: {{ .Values.audit.kafka.schemaRegistryUrl }}
        ssl:
          enabled: {{ .Values.kafka.sslEnabled }}
          keystore-certificate: {{ .Values.kafka.sslUserCertificate }}
          keystore-key: {{ .Values.kafka.sslUserKey }}
          truststore-certificate: {{ .Values.kafka.sslClusterCertificate }}

    keycloak:
      server-url: {{ .Values.keycloak.url }}/auth
      service-account:
        realm: {{ .Values.ciProject }}-external-system
        client-id: {{ .Values.keycloak.serviceAccount.clientId }}
