{{- if .Values.trembita }}
{{- if .Values.trembita.ipList }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.name }}
  annotations:
    description: "Route for {{ .Values.name }} application"
    haproxy.router.openshift.io/ip_whitelist: {{ include "soapApi.whitelist.cidr" . }}
  labels:
    app: {{ .Values.name }}
spec:
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  {{- if .Values.ingress.site }}
  host: {{ .Values.ingress.site }}-{{ .Values.namespace }}.{{ .Values.dnsWildcard }}
  {{end}}
  path: {{ .Values.ingress.path }}
  port:
    targetPort: 8080
  to:
    kind: Service
    name: {{ .Values.name }}
    weight: 100
  wildcardPolicy: None
status:
  ingress: []
{{- end }}
{{- end }}
