apiVersion: v1
kind: ConfigMap
metadata:
  name: rest-api-properties
data:
  config.yaml: |-
    data-platform:
      kafka:
        bootstrap: {{ .Values.kafka.service }}
        ssl:
          enabled: {{ .Values.kafka.sslEnable }}
    server:
      max-http-header-size: 16KB
    dso:
      url: {{ .Values.dso.url }}
    ceph:
      http-endpoint: {{ .Values.ceph.httpEndpoint }}
      bucketName: {{ .Values.ceph.bucketName }}
    lowcode-file-ceph:
      http-endpoint: {{ .Values.lowcodeFileCeph.httpEndpoint }}
      bucketName: {{ .Values.lowcodeFileCeph.bucketName }}
    datafactoryceph:
      http-endpoint: {{ .Values.datafactoryceph.httpEndpoint }}
      bucketName: {{ .Values.datafactoryceph.bucketName }}
    datafactory-response-ceph:
      http-endpoint: {{ .Values.datafactoryResponseCeph.httpEndpoint }}
      bucketName: {{ .Values.datafactoryResponseCeph.bucketName }}
    datafactory-file-ceph:
      http-endpoint: {{ .Values.datafactoryFileCeph.httpEndpoint }}
      bucketName: {{ .Values.datafactoryFileCeph.bucketName }}

    audit:
      kafka:
        bootstrap: {{ .Values.kafka.service }}
        topic: {{ .Values.audit.kafka.topic }}
        schema-registry-url: {{ .Values.audit.kafka.schemaRegistryUrl }}