{{- if and (.Values.keycloak.rulesEnabled) (((.Values.publicService).name)) }}
kind: RequestAuthentication
apiVersion: security.istio.io/v1beta1
metadata:
  name: {{ .Values.publicService.name }}-request-auth
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.publicService.name }}
  jwtRules:
    - forwardOriginalToken: true
      fromHeaders:
        - name: X-Access-Token
      issuer: {{ template "issuer.external" . }}
      jwksUri: {{ template "jwksUri.external" . }}
      {{- if .Values.keycloak.customHost }}
    - forwardOriginalToken: true
      fromHeaders:
        - name: X-Access-Token
      issuer: {{ template "custom-issuer.external" . }}
      jwksUri: {{ template "jwksUri.external" . }}
      {{- end }}
{{end}}