{{- if .Values.keycloak.rulesEnabled }}
kind: AuthorizationPolicy
apiVersion: security.istio.io/v1beta1
metadata:
  name: {{ .Values.name }}-authotiz-policy
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  rules:
    - from:
        - source:
            notRequestPrincipals:
              - '*'
      to:
        - operation:
            notPaths:
              - /actuator*
              - /openapi
              - /swagger-ui/*
              - /v3*
  action: DENY
{{end}}