{{- if and (.Values.keycloak.rulesEnabled) (((.Values.externalService).name)) }}
kind: AuthorizationPolicy
apiVersion: security.istio.io/v1beta1
metadata:
  name: {{ .Values.externalService.name }}-allow-external-authoriz-policy
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.externalService.name }}
  rules:
    - to:
      - operation:
          methods: [ "GET" ]
          paths:
            - /actuator*
            - /openapi
            - /swagger-ui/*
            - /v3*
          {{- include "external.platform.paths" . | nindent 8 }}
  action: ALLOW
{{end}}