{{- if .Values.keycloak.rulesEnabled }}
{{- range $serviceName := compact (list .Values.name ((.Values.externalService).name)) }}
kind: AuthorizationPolicy
apiVersion: security.istio.io/v1beta1
metadata:
  name: {{ $serviceName }}-authoriz-policy
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ $serviceName }}
  rules:
    - from:
        - source:
            notRequestPrincipals:
              - '*'
      to:
        - operation:
            notPaths:
              - /actuator*
              - /openapi
              - /swagger-ui/*
              - /v3*
  action: DENY
---
{{- end }}
{{- end }}