{{- if and (.Values.keycloak.rulesEnabled) (((.Values.publicService).name)) }}
kind: AuthorizationPolicy
apiVersion: security.istio.io/v1beta1
metadata:
  name: {{ .Values.publicService.name }}-allow-public-authoriz-policy
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.publicService.name }}
  rules:
    - to:
      - operation:
          methods: [ "GET", "POST" ]
          paths:
            - /actuator*
            - /openapi
            - /swagger-ui/*
            - /v3*
          {{- include "public.paths" . | nindent 8 }}
  action: ALLOW
{{end}}