{{- if .Values.keycloak.rulesEnabled }}
kind: RequestAuthentication
apiVersion: security.istio.io/v1beta1
metadata:
  name: {{ .Values.name }}-request-auth
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  jwtRules:
    {{- if eq .Values.global.deploymentMode "development" }}
    - forwardOriginalToken: true
      fromHeaders:
        - name: X-Access-Token
      issuer: {{ template "issuer.admin" . }}
      jwksUri: {{ template "jwksUri.admin" . }}
    {{- if .Values.keycloak.customHost }}
    - forwardOriginalToken: true
      fromHeaders:
        - name: X-Access-Token
      issuer: {{ template "custom-issuer.admin" . }}
      jwksUri: {{ template "jwksUri.admin" . }}
    {{- end }}
    {{- end }}
    - forwardOriginalToken: true
      fromHeaders:
        - name: X-Access-Token
      issuer: {{ template "issuer.officer" . }}
      jwksUri: {{ template "jwksUri.officer" . }}
    - forwardOriginalToken: true
      fromHeaders:
        - name: X-Access-Token
      issuer: {{ template "issuer.citizen" . }}
      jwksUri: {{ template "jwksUri.citizen" . }}
    - forwardOriginalToken: true
      fromHeaders:
        - name: X-Access-Token
      issuer: {{ template "issuer.external" . }}
      jwksUri: {{ template "jwksUri.external" . }}
      {{- if .Values.keycloak.customHost }}
    - forwardOriginalToken: true
      fromHeaders:
        - name: X-Access-Token
      issuer: {{ template "custom-issuer.officer" . }}
      jwksUri: {{ template "jwksUri.officer" . }}
    - forwardOriginalToken: true
      fromHeaders:
        - name: X-Access-Token
      issuer: {{ template "custom-issuer.citizen" . }}
      jwksUri: {{ template "jwksUri.citizen" . }}
    - forwardOriginalToken: true
      fromHeaders:
        - name: X-Access-Token
      issuer: {{ template "custom-issuer.external" . }}
      jwksUri: {{ template "jwksUri.external" . }}
      {{- end }}
{{- end }}
