{{- if .Values.global.registry.restApi.hpa.enabled }}
{{- range $serviceName := compact (list .Values.name ((.Values.externalService).name) ((.Values.publicService).name)) }}
kind: HorizontalPodAutoscaler
apiVersion: {{ include "horizontalPodAutoscaler.apiVersion" $ }}
metadata:
  name: {{ $serviceName }}
  labels:
    app: {{ $serviceName }}
    relatedNamespace: {{ $.Release.Namespace }}
spec:
  scaleTargetRef:
    kind: Deployment
    name: {{ $serviceName }}-deployment
    apiVersion: apps/v1
  minReplicas: {{ $.Values.global.registry.restApi.hpa.minReplicas }}
  maxReplicas: {{ $.Values.global.registry.restApi.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
---
{{- end }}
{{- end }}
