{{- range $index, $path := (((.Values.exposeSearchConditions).external).paths) }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ printf "ext-system-api-%d%s" $index $path | replace "/" "-" | replace "*" "" | trunc 63 | trimSuffix "-" }}
  labels:
  {{- include "external-system-api.metaLabels" $ | nindent 4 }}
  annotations:
    konghq.com/path: {{ $path | replace "/*" "" }}
    konghq.com/protocol: 'http'
    konghq.com/override: {{ $.Values.kong.ingressName }}
    konghq.com/plugins: {{ $.Values.kong.noPublicOidcPlugin }}
    ingress.kubernetes.io/service-upstream: 'true'
spec:
  ports:
    - protocol: TCP
      port: {{ $.Values.service.port }}
      targetPort: {{ $.Values.service.port }}
  sessionAffinity: None
  type: ClusterIP
  selector:
    app: {{ $.Values.externalService.name }}
{{- end }}