{{- if ((.Values.publicService).name) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: rest-api-public-swagger-properties
data:
  public-api-swagger-config.yaml: |-

    server:
      forward-headers-strategy: framework

    springdoc:
      swagger-ui:
        urls:
          - name: all
            url: /v3/api-docs/all
      group-configs:
        - group: all
          paths-to-match:
          {{- include "public.swagger.paths.deprecated" . | nindent 6 }}
          {{- include "public.swagger.search.paths" . | nindent 6 }}
    openapi:
      request:
        headers: []
{{- end }}