package ${basePackage}.kafkaapi.sequencedata;

import com.epam.digital.data.platform.kafkaapi.core.model.Sequence;
import com.epam.digital.data.platform.kafkaapi.core.service.AbstractSequenceProvider;
import java.util.Map;
import org.springframework.stereotype.Component;

@Component
public class ${className} extends AbstractSequenceProvider {

  @Override
  public Map<String, Sequence> columnSequence() {
    return Map.ofEntries(
    <#list autoGeneratedValues as value>
        Map.entry("${value.column}", new Sequence("${value.sequenceName}", "${value.pattern}"))<#sep>,</#sep>
    </#list>
      );
  }
}

