package ${basePackage}.kafkaapi.commandhandler.impl;

import com.epam.digital.data.platform.kafkaapi.core.commandhandler.Abstract${operation?capitalize}CommandHandler;
import com.epam.digital.data.platform.kafkaapi.core.commandhandler.util.EntityConverter;
import org.springframework.stereotype.Service;
import ${basePackage}.kafkaapi.tabledata.${tableDataProviderName};
import ${basePackage}.model.dto.${schemaName};
<#if autoGeneratedValueFields?has_content>
import com.epam.digital.data.platform.model.core.kafka.Request;
import ${basePackage}.kafkaapi.sequencedata.${sequenceProviderName};
</#if>

@Service
public class ${className} extends Abstract${operation?capitalize}CommandHandler<${schemaName}> {

<#if autoGeneratedValueFields?has_content>
  private final ${sequenceProviderName} sequenceProvider;
</#if>
  public ${className}(
      EntityConverter<${schemaName}> entityConverter,
      ${tableDataProviderName} tableDataProvider<#if autoGeneratedValueFields?has_content>,
      ${sequenceProviderName} sequenceProvider</#if>) {
    super(entityConverter, tableDataProvider);
<#if autoGeneratedValueFields?has_content>
    this.sequenceProvider = sequenceProvider;
</#if>
  }

<#if autoGeneratedValueFields?has_content>
  public void requestPreprocessor(Request<${schemaName}> request) {
  <#list autoGeneratedValueFields as field>
    if (request.getPayload().get${field.name?cap_first}() == null) {
      request.getPayload().set${field.name?cap_first}(sequenceProvider.generate("${field.columnName}"));
    } else {
      sequenceProvider.validate("${field.columnName}", request.getPayload().get${field.name?cap_first}());
    }
  </#list>
  }
</#if>
}
